@Restaurants_API_HostAddress = https://localhost:7113
@id = 6

# Get all restaurants
GET {{Restaurants_API_HostAddress}}/api/restaurants
Accept: application/json

###

# Get restaurant by ID
GET {{Restaurants_API_HostAddress}}/api/restaurants/{{id}}
Accept: application/json

###

# Update restaurant by ID
PUT {{Restaurants_API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
Accept: application/json

{
  "id": {{id}},
  "name": "Updated Restaurant",
  "description": "Updated description",
  "hasDelivery": true
}
